fix(ci): resolve missing notifications

diff --git a/.github/workflows/ci_sonar_scan.yaml b/.github/workflows/ci_sonar_scan.yaml
--- a/.github/workflows/ci_sonar_scan.yaml
+++ b/.github/workflows/ci_sonar_scan.yaml
@@ -110,8 +110,8 @@ jobs:
           path: ~/.sonar/cache
           key: ${{ steps.sonar-cache.outputs.cache-primary-key }}
 
-      # - name: Fail if Quality Gate failed
-      #   if: ${{ steps.qg.outputs.quality-gate-status == 'FAILED' }}
-      #   run: |
-      #     echo "SonarQube Quality Gate failed. Blocking pipeline."
-      #     exit 1
+      - name: Fail if Quality Gate failed
+        if: ${{ steps.qg.outputs.quality-gate-status == 'FAILED' }}
+        run: |
+          echo "SonarQube Quality Gate failed. Blocking pipeline."
+          exit 1
